### ISSUE TITLE
No me crea el sensor esios_gas

### ISSUE THREAD

**Issue by Vicente-Ch** [MiguelAngelLV/esios_gas#1]
Hola, tengo ha os:
Home Assistant 2022.7.0
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220706.0 - latest

Despues de descargar el repositorio y reiniciar ha. No aparece niguna entidad o sensor nuevo. Como tenia instalado la version anterior y tambien el interfaz "PVPC Hourly Pricing Card" los he eliminado ademas de eliminar "esios gas" y reiniciado. Ahora ya no me aparece ningun sensor pvpc y procedo a descargar denuevo este repositorio (https://github.com/MiguelAngelLV/esios_gas) y reiniciar. 
Pero no aparece el nuevo sensor. Tampoco encuentro la opcion para agregar mi token.
Que puede estar pasando?
saludos

**Comment by miguelangellv** [comment]
Además de instalar el componente, tienes que agregarlo en integraciones. Simplemente ve a INtegraciones -> Añadir Integración  y busca EISOS y debería salirte.

Recuerda activar en el listado tanto el de surplus como el gas compensation.

**Comment by Vicente-Ch** [comment]
Correpto, pero ahora tengo otro problema, Me da error cuando introduzco mi
token que solicite apenas una semana par leer los datos de inyeccion.
En el cuadro de dialogo donde se introduce el token , puedo marcar todas
las opciones verdad?
Volvi a habrirte un problema por github, que medio prefieres para
comunicarme contigo. Lo digo por no estar dando el coñazo por todos lados.
