### ISSUE TITLE
2023.05: Clashing with official PVPC and 'async_setup_platforms' error

### ISSUE THREAD

**Issue by diamant-x** [MiguelAngelLV/esios_gas#10]
Hola,

Desde la útlima 2023.05 tener esta y la oficial genera colisiones. En particular, desde instalar la 2023.05.2 la PVPC oficial de Core ya no arranca ya que al parecer intenta cargar archivos de este custom y les falta alguna nueva funcionalidad.

Logs:
```
Este error se originó a partir de una integración personalizada.

Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 11:09:41 (2 occurrences)
Last logged: 14:07:13

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Parece relacionado con:
https://developers.home-assistant.io/docs/integration_setup_failures?_highlight=async_setup_platforms#integrations-using-async_setup_platform o con https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards

Curiosamente la integracion custom si arranca bien, y también funcionaba bien en 2023.04 y anteriores. Es mas, diria que en la 2023.05.1 también funcionaba...
Gracias.

<html>
<body>

Versión | core-2023.5.2
-- | --
Tipo de instalación | Home Assistant OS
Desarrollo | false
Supervisor | true
Docker | true
Usuario | root
Entorno virtual | false
Versión de Python | 3.10.11
Familia de Sistema Operativo | Linux
Versión del Sistema Operativo | 6.1.21-v8

</body>
</html>

**Comment by miguelangellv** [comment]
Pero ahí el problema lo está dando un custom_component llamado pvpc_hourly_pricing.

Si es un custom_component no es el «oficial», y tampoco es este componente...

**Comment by diamant-x** [comment]
Pf, disculpa. Debía tener eso desde hace años ahí y hasta ahora no le han saltado las costuras. Cierro. Gracias.
