### ISSUE TITLE
Desde ayer 29/11/2023 no funciona

### ISSUE THREAD

**Issue by rubendediegomartinez** [MiguelAngelLV/esios_gas#11]
Desde ayer 29/11/2023 no funciona. Ayer no fue capaz de recoger los datos de hoy 30/11/2023 desde ESIOS.
He probado a reinstalar el componente custom y al crear la integración con el token que tenía me da un error.
¿Problema de con token de ESIOS? ¿Cambio en interfaces?
Nota 1: el token es del 3 de abril de 2023
Nota 2: la integración de HA-Core de PVPC funciona, pero no me da el sensor del precio de inyección de la energía a la red

¿A alguien más le pasa,? ¿Alguna solución que no haya encontrado yo?
Muchas gracias

**Comment by miguelangellv** [comment]
El proyecto lo tengo abandonado ya que ahora uso tarifas fijas. Mi recomendación es que migres al PVPC «oficial-no-oficial»: https://github.com/azogue/ha-pvpc-custom

Es el mismo componente que el oficial y creado por la misma persona, pero lo publica aparte para poder actualizarlo más rápidamente.

En esa versión ya tienes el precio de inyección.
