### ISSUE TITLE
token

### ISSUE THREAD

**Issue by Vicente-Ch** [MiguelAngelLV/esios_gas#2]
no me acepta el token que tenia para leer los datos de inyeccion. ¿debo solicitar uno nuevo?

**Comment by miguelangellv** [comment]
El token debería valer el mismo. Asegúrate de que lo estás poniendo bien o que no has excedido el número máximo de usos (desconozco si lo hay).

Este componente es una modificación del que tenía inyección solo que tiene un par de sensores extras.

**Comment by Vicente-Ch** [comment]
En las instruciones indicas que se solicite el token mandando un correo vacio a ESIOS. Cuando yo lo solicite me pidieron mi nombre completo y el motivo. Sera este el error?

**Comment by miguelangellv** [comment]
Pues ni idea. Yo cuando lo solicité simplemente puse «quiero un token» y me lo mandaron sin más preguntas.

**Comment by Vicente-Ch** [comment]
Ok, gracias. probare en otro momento o solicitare otro
