### ISSUE TITLE
Porque sumar excedentes y precio compensación gas ?

### ISSUE THREAD

**Issue by akdri** [MiguelAngelLV/esios_gas#3]
Buenos días Miguel Ángel, quería hacerte una consulta hasta donde yo tengo entendido el precio de compensación del gas, que nosotros como propietarios de instalaciones con autoconsumo no lo podemos cobrar en principio solo lo cobran las gasísticas, por ese motivo no entiendo porque sumar el precio de compensación al precio de los excedentes, antes de esta medida si tu inyectabas 1kwh y consumías 1kwh "empatabas" entre comillas porque los peajes no los puedes recuperar ni cobrar es decir que si tenias 7ct de peaje y 20ct de energía recuperabas los 20cts de energía, pero ahora por ejemplo tenemos 7ct de peajes 15ct de compensación y 12ct de energía de los cuales solo puedes recuperar los 12ct de energía que corresponden al precio del excedente pero esos 15 céntimos de compensación al gas los perdemos, en pocas palabra que nos han jod.... bien con estas medidas a todos los que teníamos autoconsumo.

Puede que no este en lo cierto pero si fuera un precio que nos fueran a pagar con los excedentes estaría sumado en el precio del excedente al igual que ya viene sumado en el precio del PVPC.

**Comment by miguelangellv** [comment]
Básicamente este componente lo hice durante las semanas que, se suponía, que sí nos iban a añadir la compensación del gas en distintas comercializadores (Próxima y Lidera por ejemplo). Desgraciadamente, antes de que se emitieran las facturas, se determinó que no podríamos cobrarlo porque a las comercializadoras se le pediría dicho impuesto.

Aún así, el componente permite ver los datos por separado  (por si te valen aunque sea solo para sufrir) y usar el precio de inyección sin gas.

Por otro lado, hay un movimiento con vista de reivindicar que se nos añada el coste del gas finalmente a nuestros excedentes. Puedes ver los detalles en este vídeo.

https://www.youtube.com/watch?v=ja64g4-f2eM


En caso de salir bien, este componente volvería a cobrar sentido, en caso contrario, pues... Tampoco molesta.

**Comment by akdri** [comment]
Buenas Miguel Ángel, muchas gracias por tu respuesta.

Aprovechando de tu experiencia, te voy a pedir si podrías hacer una modificación en tu código ya que ahora a muchos usuarios les seria de gran ayuda.

Te explico lo que haría falta.

Como sabes con la excepción Ibérica todos los contratos de libre mercado pasan a tener precio variable porque es el precio fijo de tu contrato más el precio de compensación del gas, así que cada hora cambia.

Podrías editar el componente para la gente que esta en el mercado libre, pueda insertar su precio tarifa y que le sume el la compensación del gas, yo en mi servidor tengo un sensor que capta los precios del excedente del gas y se los suma a mi tarifa, hasta ahí me defiendo programando pero me encantaría poder editar el complemento y en la grafica que se muestra el precio del PVPC del día también incluir el precio de tarifa con con la compensación del gas sumado, así a simple vista también puedes comparar si tienes una tarifa mejor o peor que el PVPC. Aparte también tengo otro sensor que calcula el porcentaje de ahorro o sobre coste de mi tarifa contra el PVPC cada hora. 

y seria estupendo si en este grafico pudiese ver el precio de mi tarifa con la suma de la compensación del gas.

![image](https://user-images.githubusercontent.com/5574939/179503243-ca8c4c60-6bc0-494e-b27e-6eb189429588.png)

Y si sacas el sensor que te sume el precio tarifa + la compensación del gas, ya ayudaras a mucha gente que no sabe programarse los sensores para calcular el precio de su factura.

![image](https://user-images.githubusercontent.com/5574939/179502285-6093fbeb-39c4-4927-ba42-ea6927f82615.png)

Como ves en la foto yo tengo:
PVPC: el precio del PVCP
Precio Tarifa: Que es el precio del kw de mi tarifa + la compensación al gas 
Precio Kw: el precio del kw de mi tarifa 
Precio excedente: al precio que nos pagan los excedentes.
Coste Kw/h: en mi caso es el consumo de red x el precio de tarifa
Precio del gas: el precio de compensación del gas por hora
Ahorro: la diferencia de precio entre PVPC y mi tarifa para saber si pago de mas o de menos respecto a PVPC

Bueno Miguel muchas gracias de antemano, un saludo.

**Comment by miguelangellv** [comment]
Ten en cuenta que hacer eso que pides es inviable ya que hay cientos de tarifas, pero puedes crearte un sensor template fácilmente dónde le sume el precio de tu tarifa al gas. Te haces ayudante dónde puedas introducir tu tarifa y simplemente le sumas el precio del gas que da mi componente.


```yaml
template:  
 
  - sensor:
     - name: "Mi tarifa + gas"
       unit_of_measurement: "€/kWh"
       state: "{{ states('input_number.mi_tarifa') | float + states('sensor.esios_gas_compensation_price') | float  }}"


```
