### ISSUE TITLE
Warning en el log de Home Assistant

### ISSUE THREAD

**Issue by contrasenda** [MiguelAngelLV/esios_gas#5]
Buenos días,

He encontrado la siguiente advertencia en el log, y piden comunicarlo al desarrollador de la integración:

`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for esios_gas using this method at custom_components/esios_gas/__init__.py, line 66: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by lucio-modrono** [comment]
Buenos días, gran integración, @MiguelAngelLV , muchas gracias por mantenerla actualizada.

Efectivamente, confirmo que se reproduce lo reportado por @contrasenda, en el log aparece este mensaje en la publicación de todos los sensores. Sería ideal contar con la corrección para poder actualizar la versión de HA a la 2023.03 sin perder esta magnífica funcionalidad.

**Comment by lucio-modrono** [comment]
Hola @MiguelAngelLV, he leído en los comentarios de la otra issue abierta de este proyecto que es posible que dejes de mantenerlo, porque ya no lo necesitas. Eso sería una lástima, pero también algo comprensible, sobre todo si la evolución del proyecto para hacerlo compatible con la nueva versión de HA supone mucho esfuerzo (yo no sabría evaluarlo).

Como alternativa, para reducir el impacto que esto pudiese acarrear al resto de usuarios de esta integración, comparto el PR que evolucionará la integración nativa PVPC de HA, incorporando el volcado de excedentes y la compensación por gas: https://github.com/home-assistant/core/pull/85769

Como soy bastante novato y no conozco el funcionamiento del proyecto HomeAssistant, no sé cuándo llegarán a consolidarse estas mejoras sobre versión...

No será lo mismo, pero en mi caso me podría servir... mucho ánimo, @MiguelAngelLV, para seguir con tus proyectos y también para compartirlos con los que no tenemos tu talento  XD

**Comment by miguelangellv** [comment]
@lucio-modrono gracias por la compresión. 

De hecho el que se fuese a integrar de forma nativa en HA era el motivo por el que dejé paré de reescribir la versión actual cuando aún la utilizaba.

Desgraciadamente tampoco sé cuanto suelen tardar en entrar estos cambios en la rama oficial.

Viendo que hoy se publicará la beta de la 2023.3 y que parece que aún no estará integrada, le echaré un ojo a este error a ver lo solvento. Inicialmente no paece muy complejo, pero a saber.

**Comment by miguelangellv** [comment]
Solucionado ;)

**Comment by lucio-modrono** [comment]
¡Genial! Muchas gracias @MiguelAngelLV , voy a desplegarlo y confirmo por aquí el resultado.

**Comment by lucio-modrono** [comment]
Confirmado, con estos cambios los mensajes de WARNING desaparecen del log de la versión 2023.02 de HomeAssistant
