### ISSUE TITLE
ESIOS API change

### ISSUE THREAD

**Issue by vidalpascual** [MiguelAngelLV/esios_gas#6]
The API change in ESIOS makes the integration get this error:

Bad auth token: 403: <StreamReader 36 bytes eof>

**Comment by miguelangellv** [comment]
¿Has actualizado a la versión que he publicado hoy?

**Comment by vidalpascual** [comment]
> ¿Has actualizado a la versión que he publicado hoy?

No lo había visto. Actualizado y funcionando. Gracias!

**Comment by vidalpascual** [comment]
> ¿Has actualizado a la versión que he publicado hoy?

No lo había visto. Actualizado y funcionando. Gracias!
