### ISSUE TITLE
No funcionan las entidades de precio del vertido a red

### ISSUE THREAD

**Issue by jouking** [MiguelAngelLV/esios_gas#8]
Desde hace un par de días han dejado de funcionar las entidades del precio por hora de vertido a red. Podrías indicarme el problema y la solución?
Gracias 
![C9FF5F1A-0D74-47EA-AFFC-203E9DACC0ED](https://user-images.githubusercontent.com/61602218/223200124-c5414645-e7bd-4815-b60d-32f6fc148282.jpeg)

**Comment by miguelangellv** [comment]
Prueba a volver eliminar la integración y volver a añadirla. Se cambió el nombre del componente de inyección y a algunos no lo pilla de forma automática.
