### ISSUE TITLE
sensor.esios_grid_injection_price   unavailable

### ISSUE THREAD

**Issue by Vicente-Ch** [MiguelAngelLV/esios_gas#9]
Hola, con esta actualizacion el sensor:
sensor.esios_grid_injection_price ha cambiado a "unavailable"

**Comment by miguelangellv** [comment]
Elimina y vuelve a añadir la integración.

**Comment by Vicente-Ch** [comment]
Ya esta, gracias.
Ahora hay 6 entidades.

**Comment by miguelangellv** [comment]
La de inyección habrá cambiado de ID, tendrás que actualizarlo dónde correspnoda.

**Comment by Vicente-Ch** [comment]
En realidad me creo otra casi gual:

sensor.esios_grid_injection_price_2

Elimine la vieja y a esta le borre el "_2" y ya me funciona bien en las autos tambien.
Gracias
